### ISSUE TITLE
NameError: name 'RNDagent' is not defined

### ISSUE THREAD

**Issue by azulgranakun** [jcwleo/curiosity-driven-exploration-pytorch#7]
There was an error when I ran the file eval.py.can you tell me why?

**Comment by azulgranakun** [comment]
i'm not find the class of RNDagent in this project.

**Comment by jcwleo** [comment]
@azulgranakun 
sorry.
RND repo is [here](https://github.com/jcwleo/random-network-distillation-pytorch).

**Comment by azulgranakun** [comment]
Thanks for your reply，I will try to fix it.

**Comment by JACKYWANG12345** [comment]
> 谢谢你的回复，我会努力解决的。

Have you solved this problem? I also encounter this problem at present, and the running data is not ideal, which is very different from the pictures given by the author. I hope you can give me a reply, which will be of great help to me.
