### ISSUE TITLE
Why Residual Blocks used?

### ISSUE THREAD

**Issue by ferreirafabio** [jcwleo/curiosity-driven-exploration-pytorch#8]
Hi, I can't wrap my head around why you're using residual connections/blocks. I've seen it in other ICM implementations as well but where is that written in the paper? On what basis do we use it?

Thanks a lot!

**Comment by jcwleo** [comment]
@ferreirafabio
https://github.com/openai/large-scale-curiosity/blob/master/dynamics.py#L55-L61
It can be found in the author's code.

**Comment by ferreirafabio** [comment]
Thanks a lot!
